
export const LOAD_USERS_START = "LOAD_USERS_START"
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS"
export const LOAD_USERS_ERROR = "LOAD_USERS_ERROR"

export const ADD_NEW_EMPLOYEE_START = 'ADD_NEW_EMPLOYEE_START'
export const ADD_NEW_EMPLOYEE_SUCCESS = 'ADD_NEW_EMPLOYEE_SUCCESS'
export const ADD_NEW_EMPLOYEE_ERROR = 'ADD_NEW_EMPLOYEE_ERROR'

export const UPDATE_EMPLOYEE_START = 'UPDATE_EMPLOYEE_START'
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS'
export const UPDATE_EMPLOYEE_ERROR = 'UPDATE_EMPLOYEE_ERROR'

export const DELETE_EMPLOYEE_START = 'DELETE_EMPLOYEE_START'
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS'
export const DELETE_EMPLOYEE_ERROR = 'DELETE_EMPLOYEE_ERROR'

export const GET_SINGLE_EMPLOYEE_START = 'GET_SINGLE_EMPLOYEE_START'
export const GET_SINGLE_EMPLOYEE_SUCCESS = 'GET_SINGLE_EMPLOYEE_SUCCESS'
export const GET_SINGLE_EMPLOYEE_ERROR = 'GET_SINGLE_EMPLOYEE_ERROR'


