
export const LOAD_ROLE_START = "LOAD_ROLE_START"
export const LOAD_ROLE_SUCCESS = "LOAD_ROLE_SUCCESS"
export const LOAD_ROLE_ERROR = "LOAD_ROLE_ERROR"

export const ADD_NEW_ROLE_START = 'ADD_NEW_ROLE_START'
export const ADD_NEW_ROLE_SUCCESS = 'ADD_NEW_ROLE_SUCCESS'
export const ADD_NEW_ROLE_ERROR = 'ADD_NEW_ROLE_ERROR'

export const UPDATE_ROLE_START = 'UPDATE_ROLE_START'
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS'
export const UPDATE_ROLE_ERROR = 'UPDATE_ROLE_ERROR'

export const GET_SINGLE_ROLE_START = 'GET_SINGLE_ROLE_START'
export const GET_SINGLE_ROLE_SUCCESS = 'GET_SINGLE_ROLE_SUCCESS'
export const GET_SINGLE_ROLE_ERROR = 'GET_SINGLE_ROLE_ERROR'
 
export const DELETE_ROLE_START = 'DELETE_ROLE_START'
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS'
export const DELETE_ROLE_ERROR = 'DELETE_ROLE_ERROR'
